### ISSUE TITLE
Is the FTMS uuid check correct?

### ISSUE THREAD

**Issue by juaoose** [Malte2036/flutter_ftms#11]
Hello there,

I must say I am very new to FTMS.

I was playing with the library and tried to connect to a FTMS cycling smart trainer, however, whenever checking if the device is FTMS device, it never looked to pass the check.

I found that the check was very particular, should this device pass this test and be considered an FTMS device?
<img width="1788" alt="image" src="https://github.com/Malte2036/flutter_ftms/assets/994594/a88d2975-bc06-454f-b2cb-16aadbb164f7">

**Comment by juaoose** [comment]
Moving ahead, it looks like `getDeviceDataTypeByBluetoothId` expects a string with a MAC address format? However, on iOS, the bluetooth library seems to return a UUID instead of that, so the method fails :(

Would it make sense , considering these iOS limitations, to use the characteristics to define what kind of device it is? For example, my device seems to have the `00002ad2` characteristic.

**Comment by Malte2036** [comment]
Thanks for pointing out this strange behavior. I should be fixed with #12. Let me know if its works now :+1:
