### ISSUE TITLE
How to get calories value

### ISSUE THREAD

**Issue by william-levi** [Malte2036/flutter_ftms#13]
Hi ! I'm wondering how to get calories value . Can you help me?

**Comment by Malte2036** [comment]
Take a look at `DeviceDataParameterName.totalEnergy`, `DeviceDataParameterName.energyPerHour`and `DeviceDataParameterName.energyPerMinute`.

**Comment by william-levi** [comment]
Hi  I get the totalEnergy value. Thanks, But another question.

The unit was already in kcal in "unit" and i notice every 10 meters is 1kcal burned.. Is this "unit" value derived from the device ? or was it prefix in the flutter ftms library code?

I wonder if the unit was meant to be joule / kilo joule ? 

Thank you for the fast reply.

**Comment by Malte2036** [comment]
The "unit" is not derived from the device. Take a look at `/lib/src/ftms/characteristic/data/device/`.

I think it is always "kcal".
