### ISSUE TITLE
Unexpected remoteId on iOS

### ISSUE THREAD

**Issue by juaoose** [Malte2036/flutter_ftms#14]
On iOS you won't get the [mac address](https://github.com/boskokg/flutter_blue_plus?tab=readme-ov-file#the-remoteid-is-different-on-android-versus-ios--macos), which leads to `FTMSBluetooth.getDeviceDataTypeByBluetoothId` failing because it expects a mac and not a uuid. You can work around it by using `getDeviceDataType`, but maybe a note on `getDeviceDataTypeWithoutConnecting` would be nice.

**Comment by Malte2036** [comment]
Fixed in `flutter_ftms` v1.1.2 🎉
