### ISSUE TITLE
Scan FTMS service by default

### ISSUE THREAD

**Issue by juaoose** [Malte2036/flutter_ftms#16]
This is more of a question:

Wouldn't it make sense for `scanForBluetoothDevices` to eventually call flutter blue plus with the FTMS services filter by default? Since the library focus is FTMS? Or maybe just mirror `FlutterBluePlus.startScan(withServices: [Guid("1826")])` so that one can pass the service to `flutter_ftms` if the user wants to default to scanning FTMS devices only.

Thanks for the responsiveness!

**Comment by Malte2036** [comment]
feel free to open a Pull Request for this 👍

**Comment by Malte2036** [comment]
https://github.com/Malte2036/flutter_ftms/pull/18

**Comment by Malte2036** [comment]
Should be fixed in [flutter_ftms: 1.1.3](https://pub.dev/packages/flutter_ftms) ✨
