### ISSUE TITLE
Bug- Connect

### ISSUE THREAD

**Issue by GustavoFonseca007** [Malte2036/flutter_ftms#3]
@Malte2036 When I click on the "Connect" button to connect to a machine that uses FTMS, Visual Studio Code presents an error.
![Captura de Tela (53)](https://github.com/Malte2036/flutter_ftms/assets/100773950/dd48a840-3aea-4791-84e5-c20db96e3cd1)

**Comment by Malte2036** [comment]
Could you run `flutter run` in an terminal and provide the full terminal log? The error you have posted is only an flutter UI error, not an `flutter_ftms` error

**Comment by GustavoFonseca007** [comment]
@Malte2036

When I click on the 'Use FTMS' button on the Bluetooth-enabled ergometer rowing machine, the following appears in the console:

 V/AudioManager( 7085): playSoundEffect   effectType: 0
V/AudioManager( 7085): querySoundEffectsEnabled...
D/BluetoothManager( 7085): getConnectionState()
D/BluetoothManager( 7085): getConnectedDevices
D/BluetoothGatt( 7085): discoverServices() - device: F5:C0:00:0C:57:AB
D/BluetoothGatt( 7085): onSearchComplete() = Device=F5:C0:00:0C:57:AB Status=0
D/FlutterBluePlugin( 7085): [onServicesDiscovered] count: 10 status: 0
I/flutter ( 7085): Found FTMS service: 00001826-0000-1000-8000-00805f9b34fb
D/BluetoothManager( 7085): getConnectionState()
D/BluetoothManager( 7085): getConnectedDevices
D/BluetoothGatt( 7085): discoverServices() - device: F5:C0:00:0C:57:AB
D/BluetoothGatt( 7085): onSearchComplete() = Device=F5:C0:00:0C:57:AB Status=0
D/FlutterBluePlugin( 7085): [onServicesDiscovered] count: 10 status: 0
I/flutter ( 7085): Found FTMS service: 00001826-0000-1000-8000-00805f9b34fb
I/flutter ( 7085): Found FTMS characteristic: 00002ace-0000-1000-8000-00805f9b34fb
D/BluetoothGatt( 7085): setCharacteristicNotification() - uuid: 00002ace-0000-1000-8000-00805f9b34fb enable: true
D/FlutterBluePlugin( 7085): [onDescriptorWrite] uuid: 00002902-0000-1000-8000-00805f9b34fb status: 0
I/flutter ( 7085): Found Feature characteristic: 00002acc-0000-1000-8000-00805f9b34fb
I/flutter ( 7085): remoteId: F5:C0:00:0C:57:ABcharacteristicUuid: 00002acc-0000-1000-8000-00805f9b34fbserviceUuid: 00001826-0000-1000-8000-00805f9b34fb
D/FlutterBluePlugin( 7085): [onCharacteristicRead] uuid: 00002acc-0000-1000-8000-00805f9b34fb status: 0
I/flutter ( 7085): featureData: [255, 255, 128, 0, 255, 255, 128, 0]

**Comment by GustavoFonseca007** [comment]
@Malte2036  When I click on the 'requestControl' button on the Bluetooth-enabled ergometer rowing machine, the following appears in the console: 
V/AudioManager( 9925): playSoundEffect   effectType: 0
V/AudioManager( 9925): querySoundEffectsEnabled...
D/BluetoothManager( 9925): getConnectionState()
D/BluetoothManager( 9925): getConnectedDevices
D/BluetoothGatt( 9925): discoverServices() - device: F5:C0:00:0C:57:AB
D/BluetoothGatt( 9925): onSearchComplete() = Device=F5:C0:00:0C:57:AB Status=0
D/FlutterBluePlugin( 9925): [onServicesDiscovered] count: 10 status: 0
I/flutter ( 9925): Found FTMS service: 00001826-0000-1000-8000-00805f9b34fb
D/FlutterBluePlugin( 9925): [onCharacteristicWrite] uuid: 00002ad9-0000-1000-8000-00805f9b34fb status: 0
E/        ( 9925): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0102]
D/BluetoothGatt( 9925): onConnectionUpdated() - Device=F5:C0:00:0C:57:AB interval=16 latency=0 timeout=256 status=0

**Comment by GustavoFonseca007** [comment]
@Malte2036 

 When I click on the 'reset' button on the Bluetooth-enabled ergometer rowing machine, the following appears in the console:

V/AudioManager( 9925): playSoundEffect   effectType: 0
V/AudioManager( 9925): querySoundEffectsEnabled...
D/BluetoothManager( 9925): getConnectionState()
D/BluetoothManager( 9925): getConnectedDevices
D/BluetoothGatt( 9925): discoverServices() - device: F5:C0:00:0C:57:AB
D/BluetoothGatt( 9925): onSearchComplete() = Device=F5:C0:00:0C:57:AB Status=0
D/FlutterBluePlugin( 9925): [onServicesDiscovered] count: 10 status: 0
I/flutter ( 9925): Found FTMS service: 00001826-0000-1000-8000-00805f9b34fb
D/FlutterBluePlugin( 9925): [onCharacteristicWrite] uuid: 00002ad9-0000-1000-8000-00805f9b34fb status: 0

**Comment by GustavoFonseca007** [comment]
@Malte2036 
When I click on the 'setTargetSpeed' button on the Bluetooth-enabled ergometer rowing machine, the following appears in the console:

V/AudioManager(10587): playSoundEffect   effectType: 0
V/AudioManager(10587): querySoundEffectsEnabled...
D/BluetoothManager(10587): getConnectionState()
D/BluetoothManager(10587): getConnectedDevices
D/BluetoothGatt(10587): discoverServices() - device: F5:C0:00:0C:57:AB
D/BluetoothGatt(10587): onSearchComplete() = Device=F5:C0:00:0C:57:AB Status=0
D/FlutterBluePlugin(10587): [onServicesDiscovered] count: 10 status: 0
I/flutter (10587): Found FTMS service: 00001826-0000-1000-8000-00805f9b34fb
E/        (10587): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0102]
D/FlutterBluePlugin(10587): [onCharacteristicWrite] uuid: 00002ad9-0000-1000-8000-00805f9b34fb status: 0
E/        (10587): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0102]
D/BluetoothGatt(10587): onConnectionUpdated() - Device=F5:C0:00:0C:57:AB interval=16 latency=0 timeout=256 status=0

**Comment by GustavoFonseca007** [comment]
@Malte2036 
When I click on the 'setTargetInclination' button on the Bluetooth-enabled ergometer rowing machine, the following appears in the console:

V/AudioManager(11051): playSoundEffect   effectType: 0
V/AudioManager(11051): querySoundEffectsEnabled...
D/BluetoothManager(11051): getConnectionState()
D/BluetoothManager(11051): getConnectedDevices
E/flutter (11051): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Cannot discoverServices whiledevice is not connected. State == BluetoothDeviceState.disconnected

**Comment by GustavoFonseca007** [comment]
@Malte2036 
When I click on the 'setTargetResistanceLevel' button on the Bluetooth-enabled ergometer rowing machine, the following appears in the console:

V/AudioManager(11282): querySoundEffectsEnabled...
D/BluetoothManager(11282): getConnectionState()
D/BluetoothManager(11282): getConnectedDevices
D/BluetoothGatt(11282): discoverServices() - device: F5:C0:00:0C:57:AB
D/BluetoothGatt(11282): onSearchComplete() = Device=F5:C0:00:0C:57:AB Status=0
D/FlutterBluePlugin(11282): [onServicesDiscovered] count: 10 status: 0
I/flutter (11282): Found FTMS service: 00001826-0000-1000-8000-00805f9b34fb
D/FlutterBluePlugin(11282): [onCharacteristicWrite] uuid: 00002ad9-0000-1000-8000-00805f9b34fb status: 0

**Comment by GustavoFonseca007** [comment]
@Malte2036 

When I click on the 'setTargetPower' button on the Bluetooth-enabled ergometer rowing machine, the following appears in the console:

V/AudioManager(11668): playSoundEffect   effectType: 0
V/AudioManager(11668): querySoundEffectsEnabled...
D/BluetoothManager(11668): getConnectionState()
D/BluetoothManager(11668): getConnectedDevices
D/BluetoothGatt(11668): discoverServices() - device: F5:C0:00:0C:57:AB
D/BluetoothGatt(11668): onSearchComplete() = Device=F5:C0:00:0C:57:AB Status=0
D/FlutterBluePlugin(11668): [onServicesDiscovered] count: 10 status: 0
I/flutter (11668): Found FTMS service: 00001826-0000-1000-8000-00805f9b34fb
D/FlutterBluePlugin(11668): [onCharacteristicWrite] uuid: 00002ad9-0000-1000-8000-00805f9b34fb status: 0

**Comment by GustavoFonseca007** [comment]
@Malte2036 
When I click on the 'setTargetHeartRate' button on the Bluetooth-enabled ergometer rowing machine, the following appears in the console:

V/AudioManager(12095): playSoundEffect   effectType: 0
V/AudioManager(12095): querySoundEffectsEnabled...
D/BluetoothManager(12095): getConnectionState()
D/BluetoothManager(12095): getConnectedDevices
D/BluetoothGatt(12095): discoverServices() - device: F5:C0:00:0C:57:AB
D/BluetoothGatt(12095): onSearchComplete() = Device=F5:C0:00:0C:57:AB Status=0
D/FlutterBluePlugin(12095): [onServicesDiscovered] count: 10 status: 0
I/flutter (12095): Found FTMS service: 00001826-0000-1000-8000-00805f9b34fb
D/FlutterBluePlugin(12095): [onCharacteristicWrite] uuid: 00002ad9-0000-1000-8000-00805f9b34fb status: 0

**Comment by GustavoFonseca007** [comment]
@Malte2036 

When I click on the 'startOrResume' button on the Bluetooth-enabled ergometer rowing machine, the following appears in the console:

V/AudioManager(13326): playSoundEffect   effectType: 0
V/AudioManager(13326): querySoundEffectsEnabled...
D/BluetoothManager(13326): getConnectionState()
D/BluetoothManager(13326): getConnectedDevices
D/BluetoothGatt(13326): discoverServices() - device: F5:C0:00:0C:57:AB
D/BluetoothGatt(13326): onSearchComplete() = Device=F5:C0:00:0C:57:AB Status=0
D/FlutterBluePlugin(13326): [onServicesDiscovered] count: 10 status: 0
I/flutter (13326): Found FTMS service: 00001826-0000-1000-8000-00805f9b34fb
D/FlutterBluePlugin(13326): [onCharacteristicWrite] uuid: 00002ad9-0000-1000-8000-00805f9b34fb status: 0

**Comment by GustavoFonseca007** [comment]
When I click on the 'stopOrPause' button on the Bluetooth-enabled ergometer rowing machine, the following appears in the console:
V/AudioManager(13726): playSoundEffect   effectType: 0
V/AudioManager(13726): querySoundEffectsEnabled...
D/BluetoothManager(13726): getConnectionState()
D/BluetoothManager(13726): getConnectedDevices
D/BluetoothGatt(13726): discoverServices() - device: F5:C0:00:0C:57:AB
D/BluetoothGatt(13726): onSearchComplete() = Device=F5:C0:00:0C:57:AB Status=0
D/FlutterBluePlugin(13726): [onServicesDiscovered] count: 10 status: 0
I/flutter (13726): Found FTMS service: 00001826-0000-1000-8000-00805f9b34fb
D/BluetoothGatt(13726): onConnectionUpdated() - Device=F5:C0:00:0C:57:AB interval=16 latency=0 timeout=256 status=0
D/FlutterBluePlugin(13726): [onCharacteristicWrite] uuid: 00002ad9-0000-1000-8000-00805f9b34fb status: 0

**Comment by Malte2036** [comment]
> @Malte2036
> 
> When I click on the 'Use FTMS' button on the Bluetooth-enabled ergometer rowing machine, the following appears in the console:
> 
> V/AudioManager( 7085): playSoundEffect effectType: 0 V/AudioManager( 7085): querySoundEffectsEnabled... D/BluetoothManager( 7085): getConnectionState() D/BluetoothManager( 7085): getConnectedDevices D/BluetoothGatt( 7085): discoverServices() - device: F5:C0:00:0C:57:AB D/BluetoothGatt( 7085): onSearchComplete() = Device=F5:C0:00:0C:57:AB Status=0 D/FlutterBluePlugin( 7085): [onServicesDiscovered] count: 10 status: 0 I/flutter ( 7085): Found FTMS service: 00001826-0000-1000-8000-00805f9b34fb D/BluetoothManager( 7085): getConnectionState() D/BluetoothManager( 7085): getConnectedDevices D/BluetoothGatt( 7085): discoverServices() - device: F5:C0:00:0C:57:AB D/BluetoothGatt( 7085): onSearchComplete() = Device=F5:C0:00:0C:57:AB Status=0 D/FlutterBluePlugin( 7085): [onServicesDiscovered] count: 10 status: 0 I/flutter ( 7085): Found FTMS service: 00001826-0000-1000-8000-00805f9b34fb I/flutter ( 7085): Found FTMS characteristic: 00002ace-0000-1000-8000-00805f9b34fb D/BluetoothGatt( 7085): setCharacteristicNotification() - uuid: 00002ace-0000-1000-8000-00805f9b34fb enable: true D/FlutterBluePlugin( 7085): [onDescriptorWrite] uuid: 00002902-0000-1000-8000-00805f9b34fb status: 0 I/flutter ( 7085): Found Feature characteristic: 00002acc-0000-1000-8000-00805f9b34fb I/flutter ( 7085): remoteId: F5:C0:00:0C:57:ABcharacteristicUuid: 00002acc-0000-1000-8000-00805f9b34fbserviceUuid: 00001826-0000-1000-8000-00805f9b34fb D/FlutterBluePlugin( 7085): [onCharacteristicRead] uuid: 00002acc-0000-1000-8000-00805f9b34fb status: 0 I/flutter ( 7085): featureData: [255, 255, 128, 0, 255, 255, 128, 0]

This is the interesting part. What is in the next lines of this logs? Are there more lines with number arrays like " [255, 255, 128, 0, 255, 255, 128, 0]"?

This line ("Found FTMS characteristic: 00002ace-0000-1000-8000-00805f9b34fb") indicates your device is an cross trainer ("2ace") not an rower. Which device are you using exactly?

**Comment by GustavoFonseca007** [comment]
@Malte2036 My cell phone is a Huawei, my laptop is an HP, and the machine is a rower.

**Comment by Malte2036** [comment]
has the rower the latest software version? Are there any other arrays in the console? And please try the example again with `flutter_ftms` 0.8.0.

The error in the screenshot is an flutter error (not an error of `flutter_ftms`). Can you run the app from your terminal directly with `flutter run`.

**Comment by Malte2036** [comment]
In the latest example on github your flutter error should be resolved

**Comment by GustavoFonseca007** [comment]
> has the rower the latest software version? Are there any other arrays in the console? And please try the example again with `flutter_ftms` 0.8.0.
> 
> The error in the screenshot is an flutter error (not an error of `flutter_ftms`). Can you run the app from your terminal directly with `flutter run`.

 I used "flutter run," so I was able to get those messages on the console. I sent you everything that appeared on the console
