### ISSUE TITLE
behave like an FTMS device

### ISSUE THREAD

**Issue by december-soul** [Malte2036/flutter_ftms#8]
I am currently planning a project in which my mobile device is to behave like a sensor. 
This means that data is to be sent to a Garmin watch, for example.
I would therefore have to behave like a sensor myself.
If I understand correctly, this project is more about integrating sensors and not about being a sensor myself. Which is great.

Would this be possible and could it be realized in this project?

Regards
Patrick

**Comment by Malte2036** [comment]
Hey,

this project can only integrate FTMS devices. You cannot simulate an FTMS device with this plugin.
