### ISSUE TITLE
Error when using writeMachineControlPointCharacteristic function

### ISSUE THREAD

**Issue by william-levi** [Malte2036/flutter_ftms#9]
I was using the example in your repo and i got this error
Unhandled Exception: write not supported on characteristic: 00002ad9-0000-1000-8000-00805f9b34fb

**Comment by Malte2036** [comment]
Maybe your ftms device does not support writing on the "Fitness Machine Control Point" (00002ad9-0000-1000-8000-00805f9b34fb)

**Comment by Malte2036** [comment]
@william-levi There was a bug in my [code](https://github.com/Malte2036/flutter_ftms/commit/ebc42bc50c1783a1c7be8079627bb808a83fb226), which should be fixed now.

Please let me know if it works now 👍

**Comment by william-levi** [comment]
wow thank you ! I'll check it now

**Comment by william-levi** [comment]
Hi ! I have tested this with the latest updates. And still I can't send any commands. There are no errors thou.
Is it possible that my device is not following the standard protocol ?
